replicaCount: 2

image:
  repository: quay.io/cbusse_openshift/hyperfleet-operator
  tag: ""
  pullPolicy: IfNotPresent

awsRegion: ""
baseDomain: ""

postgres:
  secretName: postgres-dsn
  secretKey: dsn

hyperfleetdb:
  bucketCount: 1

serviceAccount:
  create: true
  name: hyperfleet-operator
  annotations: {}

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

compactor:
  enabled: true
  interval: 5m
  retention: 24h
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 32Mi

nodeSelector: {}
tolerations: []
