apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hyperfleet-operator.fullname" . }}-mc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hyperfleet-operator.labels" . | nindent 4 }}
data:
  clusters.yaml: |
    {{- .Values.managementClusters | toYaml | nindent 4 }}
