---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - hyperfleet.io
  resources:
  - clusters
  - manifests
  - nodepools
  - placements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hyperfleet.io
  resources:
  - clusters/finalizers
  - manifests/finalizers
  - nodepools/finalizers
  verbs:
  - update
- apiGroups:
  - hyperfleet.io
  resources:
  - clusters/status
  - manifests/status
  - nodepools/status
  - placements/status
  verbs:
  - get
  - patch
  - update
