apiVersion: hyperfleet.io/v1alpha1
kind: Placement
metadata:
  labels:
    app.kubernetes.io/name: hyperfleet-operator
    app.kubernetes.io/managed-by: kustomize
  name: placement-sample
spec:
  # TODO(user): Add fields here
